controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_accueil:
    path: /
    controller: App\Controller\AccueilController::index

# config/routes.yaml


accueil:
    path: /
    controller: App\Controller\CatalogueController::index

plats:
    path: /plats
    controller: App\Controller\CatalogueController::plats


